name: Deploy (production)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Стартуем на Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Клонируем весь репозиторий в runner

      - name: Copy files to the server
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -vzrO --delete
          path: services/colorbook-bot/
          remote_path: /opt/colorbook/main/
          remote_host: ${{ secrets.SERVER_IP }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
