name: Deploy to the Server (production)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Стартуем на Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Клонируем весь репозиторий в runner

      - name: Copy files to the server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "server/*"  # from
          target: "/colorbook/src/"  # to
          strip_components: 1

      - name: Restart service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -f /colorbook/src/setup.sh
            rm -f /colorbook/bot.log
            rm -f /colorbook/bot.err
            sudo /usr/bin/systemctl restart coloring-bot.service