name: Deploy to the Server (develop)

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest  # Стартуем на Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Клонируем весь репозиторий в runner

      - name: Copy files to the server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "services/colorbook-bot/*"  # from
          target: "/opt/colorbook-dev/app/"  # to
          strip_components: 2